# Generated by Django 5.1.15 on 2026-08-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_weatherdailyagg_weatherhourlyagg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('product', models.CharField(default='MOD10A1', max_length=20, verbose_name='产品短名')),
                ('concept_id', models.CharField(default='C2565093311-NSIDC_CPRD', max_length=50, verbose_name='CMR Concept ID')),
                ('min_lon', models.FloatField(default=85.5, verbose_name='最小经度')),
                ('max_lon', models.FloatField(default=91.1, verbose_name='最大经度')),
                ('min_lat', models.FloatField(default=45.0, verbose_name='最小纬度')),
                ('max_lat', models.FloatField(default=49.2, verbose_name='最大纬度')),
                ('tile_dataset_name', models.CharField(default='modis-snow', help_text='对应 settings.TILE_DATASETS 的 key', max_length=50, verbose_name='瓦片数据集名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RasterJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='数据日期')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('DOWNLOADING', '下载中'), ('RENDERING', '渲染中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('SKIPPED', '已跳过')], default='PENDING', max_length=20, verbose_name='状态')),
                ('celery_task_id', models.CharField(blank=True, max_length=64, verbose_name='Celery 任务 ID')),
                ('source_files', models.JSONField(default=list, verbose_name='源文件列表')),
                ('tile_count', models.IntegerField(default=0, verbose_name='瓦片数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('triggered_by', models.CharField(default='manual', max_length=50, verbose_name='触发方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='data.rasterdataset', verbose_name='所属数据集')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('dataset', 'date')},
            },
        ),
    ]
