"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(env_path=None):
    """极简 .env 加载器：把 KEY=VALUE 写入 os.environ（不覆盖已有变量）。

    避免引入 python-dotenv 依赖；支持空行与 # 注释。
    """
    env_file = Path(env_path) if env_path else BASE_DIR / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        if key:
            os.environ.setdefault(key, value)


_load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量 DJANGO_SECRET_KEY 读取；本地开发请在项目根目录创建 .env（见 .env.example）
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-placeholder-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "data.apps.DataConfig",
    "rest_framework",
    "django_filters",
    'django_apscheduler',  # 注册 apscheduler 应用
    "drf_spectacular",
    "django_celery_results",  # Celery 结果持久化到数据库
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # 从环境变量读取（本地开发写在 .env 里，见 .env.example）
        'NAME': os.environ.get('POSTGRES_DB', 'eeqsDB'),
        'USER': os.environ.get('POSTGRES_USER', 'shy'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '15432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/



TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings - 开发环境允许所有来源
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://*",
    "https://*",
]

# Tile distribution settings (dev defaults)
TILE_DATASETS = {
    "default": BASE_DIR / "data" / "tiles",
    "modis-snow": BASE_DIR / "data" / "tiles_modis_snow",
}
TILE_ALLOWED_EXTENSIONS = ["png", "jpg", "jpeg", "webp", "pbf"]
TILE_MIN_ZOOM = 0
TILE_MAX_ZOOM = 22
TILE_CACHE_CONTROL = "public, max-age=3600"

# Hydrology forecast settings
HYDROLOGY_MODEL_SCRIPT_PATH = os.environ.get(
    "HYDROLOGY_MODEL_SCRIPT_PATH",
    r"F:\模型脚本\lstm\lstm_enkf_online_meteorology.py",
)
HYDROLOGY_MODEL_ENTRYPOINT = "run_forecast"
HYDROLOGY_DEFAULT_MODEL_NAME = "lstm"
HYDROLOGY_DEFAULT_MODEL_VERSION = "v1"
HYDROLOGY_RETRY_ATTEMPTS = 3
HYDROLOGY_RETRY_DELAY_SECONDS = 300
HYDROLOGY_DAILY_RUN_HOUR = 1
HYDROLOGY_DAILY_RUN_MINUTE = 0

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Django Tutorial API',
    'DESCRIPTION': 'API documentation generated by drf-spectacular',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/',
}

# =============================================================================
# Celery Configuration
# =============================================================================

# Redis broker URL (database 0)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")

# Store task results in the database via django-celery-results
CELERY_RESULT_BACKEND = "django-db"

# Serialize task arguments using JSON (safe and human-readable)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Timezone handling — reuse Django's TIME_ZONE
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False  # Let Celery use local timezone (Asia/Shanghai)

# Task execution limits (prevent runaway model scripts)
CELERY_TASK_TIME_LIMIT = 3600          # hard limit: 1 hour
CELERY_TASK_SOFT_TIME_LIMIT = 3300     # soft limit: 55 minutes (raises SoftTimeLimitExceeded)

# Reliability settings
CELERY_TASK_ACKS_LATE = True           # Acknowledge after task finishes (prevents loss on worker crash)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Fetch one task at a time per worker (good for long-running tasks)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Synchronous execution for unit tests (override in test settings if needed)
CELERY_TASK_ALWAYS_EAGER = False

# Celery Beat schedule — runs alongside APScheduler during the transition period.
# APScheduler will be removed once Celery Beat is verified stable.
CELERY_BEAT_SCHEDULE = {
    "import-weather-data": {
        "task": "data.tasks.import_data_task",
        "schedule": 1800.0,  # 30 minutes in seconds
    },
    "daily-hydrology-forecast": {
        "task": "data.tasks.hydrology_forecast_task",
        "schedule": crontab(hour=1, minute=0),  # daily at 01:00
        "kwargs": {"triggered_by_id": None, "source": "celery_beat"},
    },
    "daily-raster-sync": {
        "task": "data.tasks.raster_sync_task",
        "schedule": crontab(hour=2, minute=20),  # daily at 02:20
        "kwargs": {"dataset_id": 1, "days_back": 16, "triggered_by": "schedule"},
    },
}

# Toggle between sync and async hydrology forecast (for transition / rollback)
HYDROLOGY_ASYNC_MODE = False  # Set True to enable Celery dispatch; False keeps synchronous APScheduler path
